# Generated by Django 5.1.3 on 2024-12-24 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_comment_model_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_model',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase_model',
            name='user',
        ),
        migrations.AddField(
            model_name='purchase_model',
            name='product',
            field=models.ManyToManyField(to='books.book_model'),
        ),
        migrations.AddField(
            model_name='purchase_model',
            name='user',
            field=models.ManyToManyField(related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
