# Generated by Django 5.1.3 on 2024-12-24 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_purchase_model_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_model',
            name='product',
        ),
        migrations.AddField(
            model_name='purchase_model',
            name='product',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='books.book_model'),
        ),
    ]
