# Generated by Django 5.1.3 on 2024-12-24 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_purchase_model_product_purchase_model_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_model',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.book_model'),
        ),
    ]
