# Generated by Django 5.1.3 on 2024-12-24 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_purchase_model_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_model',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book_model'),
        ),
    ]
