# Generated by Django 5.1.3 on 2024-12-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_purchase_model_product'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_model',
            name='category',
        ),
        migrations.AddField(
            model_name='book_model',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='books', to='categories.category'),
        ),
    ]
