# Generated by Django 5.1.3 on 2024-12-24 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_book_model_category_book_model_category'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_model',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='purchase_model',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book_model'),
        ),
    ]
