# Generated by Django 5.1.3 on 2024-12-24 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_model_category_and_more'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_model',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='categories.category'),
        ),
    ]
